parameters:
#    wesamly_kotobi.example.class: Wesamly\KotobiBundle\Example

services:
#    wesamly_kotobi.example:
#        class: %wesamly_kotobi.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
